export const TEL_AVIV_KEY = "215854";
export const ADD_NEW_FAVORITE_ACTION = "ADD_NEW_FAVORITE";
export const SET_SELECTED_LOCATION_ACTION = "SET_SELECTED_LOCATION";
export const SET_LOCATION_FORECASTS_ACTION = "SET_LOCATION_FORECASTS";
export const SET_CURRENT_WEATHER_LOCATION_ACTION = "SET_CURRENT_WEATHER_LOCATION";
export const WEATHER_LOCAL_STORAGE = "Weather";
